### ISSUE TITLE
List not refreshing when going to next page

### ISSUE THREAD

**Issue by m-decarli** [heddendorp/section-app-client#830] opened 2023-08-26 14:11 UTC
Bug was noticed on https://tumi.esn.world/tenant/codes.

When changing the number of displayed entries or going to the next page, the entries wont change. Therefore only the first 20 entries can be seen right now

Was reproduced on Firefox, Firefox on Android and Edge

**Comment by heddendorp** [comment] 2023-08-27 14:39
Duplicate of #831

**Closed by heddendorp** 2023-08-27 14:39 UTC
